# Generated by Django 5.1.1 on 2024-10-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_room_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='name',
        ),
    ]
