# Generated by Django 5.1.1 on 2024-12-28 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_rename_name_message_room_rename_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
